//! What the app says about its own licensing.
//!
//! Hydra is AGPL-3.0-only, and is built from some nine hundred open-source
//! packages whose licences ask that their copyright notice travel with the
//! binary. Until this module existed none of that was in the product: the
//! licence lived in the repository, the notices lived in a build machine's
//! package cache, and a user who installed Hydra received neither.
//!
//! All three documents are embedded rather than read from disk at runtime.
//! An installed app has no repository beside it, and a notice file that can
//! go missing is a notice file that will.
//!
//! The notices are generated — `scripts/licenses.py`, via `just licenses` —
//! from the GUI's own dependency graph, so they describe what this binary
//! actually links rather than what someone remembered to list.

use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

/// Hydra's own licence, verbatim.
const LICENSE_TEXT: &str = include_str!("../../../../LICENSE");

/// The commercial-licence offer: who needs one, and who does not. Shown
/// beside the licence because "must I open-source my work?" is the first
/// question the AGPL raises and the licence text itself answers it only in
/// legal prose.
const COMMERCIAL_TEXT: &str = include_str!("../../../../COMMERCIAL_LICENSE.md");

/// Generated by `just licenses`. See `scripts/licenses.py` for the shape.
const NOTICES_JSON: &str = include_str!("../../resources/third-party-licenses.json");

/// Where the corresponding source can be obtained — the AGPL's central
/// promise, and the one thing a binary must say out loud to keep it.
const SOURCE_URL: &str = "https://github.com/neeraip/hydra";

/// One licence file a package ships, named so a reader can tell which half
/// of a dual licence they are looking at.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NoticeFile {
    /// The file's name in the package (`LICENSE`, `LICENSE-APACHE`, …).
    pub name: String,
    /// Index into the shared text pool.
    pub text: usize,
}

/// A generated component entry, as stored.
#[derive(Debug, Clone, Deserialize)]
struct StoredComponent {
    name: String,
    version: String,
    ecosystem: String,
    spdx: String,
    url: String,
    /// `[name, text index]` pairs — empty when the package ships no licence
    /// file of its own, which leaves `spdx` and `url` as the whole notice.
    files: Vec<(String, usize)>,
}

#[derive(Debug, Deserialize)]
struct StoredNotices {
    texts: Vec<String>,
    components: Vec<StoredComponent>,
}

/// One dependency the app ships, as the About panel lists it.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ThirdPartyComponent {
    pub name: String,
    pub version: String,
    /// `"rust"` or `"npm"` — which half of the app it belongs to.
    pub ecosystem: String,
    /// The declared SPDX expression, empty when the package declares none.
    pub spdx: String,
    /// The package's own home, empty when it states none.
    pub url: String,
    pub files: Vec<NoticeFile>,
}

/// Hydra's licensing, without the parts that are megabytes long.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct LicenseInfo {
    /// SPDX identifier of Hydra's own licence.
    pub spdx: String,
    /// The full licence text.
    pub text: String,
    /// The commercial-licence document, in Markdown.
    pub commercial: String,
    /// Where the corresponding source is published.
    pub source_url: String,
}

fn notices() -> &'static StoredNotices {
    static PARSED: OnceLock<StoredNotices> = OnceLock::new();
    PARSED.get_or_init(|| {
        // The file is generated and embedded at compile time, so a parse
        // failure is a broken build rather than a runtime condition — and
        // the test below is what catches it.
        serde_json::from_str(NOTICES_JSON).unwrap_or(StoredNotices {
            texts: Vec::new(),
            components: Vec::new(),
        })
    })
}

#[tauri::command]
/// Hydra's own licence, the commercial-licence document, and the source URL.
pub fn get_license_info() -> LicenseInfo {
    LicenseInfo {
        spdx: env!("CARGO_PKG_LICENSE").to_string(),
        text: LICENSE_TEXT.to_string(),
        commercial: COMMERCIAL_TEXT.to_string(),
        source_url: SOURCE_URL.to_string(),
    }
}

#[tauri::command]
/// Every open-source component this build ships, alphabetically.
///
/// The licence *texts* are deliberately left behind: they are a megabyte
/// between them, most of it duplicated, and the panel shows one at a time.
/// Callers fetch a text with [`get_third_party_license_text`] when a reader
/// asks for it.
pub fn list_third_party_components() -> Vec<ThirdPartyComponent> {
    notices()
        .components
        .iter()
        .map(|c| ThirdPartyComponent {
            name: c.name.clone(),
            version: c.version.clone(),
            ecosystem: c.ecosystem.clone(),
            spdx: c.spdx.clone(),
            url: c.url.clone(),
            files: c
                .files
                .iter()
                .map(|(name, text)| NoticeFile {
                    name: name.clone(),
                    text: *text,
                })
                .collect(),
        })
        .collect()
}

#[tauri::command]
/// One licence text from the shared pool, by the index a component names.
pub fn get_third_party_license_text(index: usize) -> Result<String, String> {
    notices()
        .texts
        .get(index)
        .cloned()
        .ok_or_else(|| format!("no licence text at index {index}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The window's permissions, including which URLs the app may hand to
    /// the system opener.
    const CAPABILITIES: &str = include_str!("../../capabilities/default.json");

    /// Every `[text](target)` in a Markdown document, targets only.
    fn markdown_link_targets(md: &str) -> Vec<String> {
        let mut out = Vec::new();
        let bytes: Vec<char> = md.chars().collect();
        let mut i = 0;
        while i + 1 < bytes.len() {
            if bytes[i] == ']' && bytes[i + 1] == '(' {
                let start = i + 2;
                if let Some(len) = bytes[start..].iter().position(|c| *c == ')') {
                    out.push(bytes[start..start + len].iter().collect());
                    i = start + len;
                }
            }
            i += 1;
        }
        out
    }

    /// The URL the app will actually be asked to open for a link target.
    ///
    /// Mirrors `repoLink` in `hooks/licenses.ts`: a target with no scheme
    /// is a sibling file in the repository, which resolves against the
    /// published source once the document is inside an installed app. The
    /// two are hand-mirrored, so the rule is asserted on both sides.
    fn resolved(target: &str) -> Option<String> {
        if target.starts_with('#') {
            return None; // in-document, never handed to the opener
        }
        if target.contains("://") || target.contains(':') && !target.starts_with('/') {
            return Some(target.to_string());
        }
        Some(format!(
            "{SOURCE_URL}/blob/main/{}",
            target.trim_start_matches('/')
        ))
    }

    /// Whether the opener scope in `capabilities/default.json` admits `url`.
    ///
    /// The plugin matches each `allow` entry as a glob, and every entry we
    /// write is a scheme followed by `*`, so a prefix test says the same
    /// thing without pulling in a glob crate to check a config file.
    fn opener_allows(url: &str) -> bool {
        let caps: serde_json::Value =
            serde_json::from_str(CAPABILITIES).expect("capabilities file must parse");
        let permissions = caps["permissions"].as_array().expect("permissions array");
        permissions
            .iter()
            .filter(|p| p["identifier"] == "opener:allow-open-url")
            .filter_map(|p| p["allow"].as_array())
            .flatten()
            .filter_map(|entry| entry["url"].as_str())
            .any(|pattern| match pattern.strip_suffix('*') {
                Some(prefix) => url.starts_with(prefix),
                None => url == pattern,
            })
    }

    #[test]
    fn every_link_in_the_embedded_documents_can_be_opened() {
        // The commercial document ends by inviting the reader to ask, over
        // a `mailto:` link. The opener scope allowed `https://*` and
        // nothing else, so that invitation did nothing at all — no error,
        // no mail client, no sign that a link had been pressed.
        //
        // A document shipped inside the app is a promise that its links
        // work, and the only thing that can keep it is the permission this
        // reads.
        for target in markdown_link_targets(COMMERCIAL_TEXT) {
            let Some(url) = resolved(&target) else {
                continue;
            };
            assert!(
                opener_allows(&url),
                "the commercial-licence document links to {url}, which the \
                 opener scope in capabilities/default.json does not allow — \
                 the link would silently do nothing",
            );
        }
    }

    #[test]
    fn the_source_link_is_openable() {
        assert!(opener_allows(SOURCE_URL));
    }

    #[test]
    fn an_unlisted_scheme_is_still_refused() {
        // The scope is a scope, not a formality: widening it for `mailto:`
        // must not have widened it for everything.
        assert!(!opener_allows("file:///etc/passwd"));
        assert!(!opener_allows("http://example.com"));
    }

    #[test]
    fn embedded_notices_parse() {
        // `notices()` swallows a parse error into an empty document so the
        // app degrades rather than panics; this is the check that turns
        // that emptiness into a build failure.
        let parsed: Result<StoredNotices, _> = serde_json::from_str(NOTICES_JSON);
        let doc = parsed.expect("generated notices file must parse");
        assert!(
            doc.components.len() > 100,
            "the app links hundreds of packages; {} suggests a truncated file",
            doc.components.len()
        );
        assert!(!doc.texts.is_empty(), "no licence texts were collected");
    }

    #[test]
    fn every_component_reference_resolves() {
        // A dangling index would show a reader an empty licence — or
        // someone else's.
        let doc = notices();
        for c in &doc.components {
            for (name, index) in &c.files {
                assert!(
                    *index < doc.texts.len(),
                    "{} {} references text {index} ({name}), but only {} exist",
                    c.name,
                    c.version,
                    doc.texts.len()
                );
            }
        }
    }

    #[test]
    fn a_component_with_no_licence_file_still_names_its_licence() {
        // 80-odd packages ship no licence file at all. Their entry is the
        // whole notice they get, so it has to carry the SPDX id — an entry
        // with neither text nor identifier says nothing.
        let doc = notices();
        for c in doc.components.iter().filter(|c| c.files.is_empty()) {
            assert!(
                !c.spdx.is_empty(),
                "{} {} ships no licence file and declares no licence either",
                c.name,
                c.version
            );
        }
    }

    #[test]
    fn text_lookup_rejects_an_index_past_the_pool() {
        let out_of_range = notices().texts.len();
        assert!(get_third_party_license_text(out_of_range).is_err());
    }

    #[test]
    fn license_info_carries_the_agpl_and_the_source() {
        let info = get_license_info();
        assert_eq!(info.spdx, "AGPL-3.0-only");
        assert!(info.text.contains("GNU AFFERO GENERAL PUBLIC LICENSE"));
        assert!(info.commercial.contains("Commercial License"));
        assert!(info.source_url.starts_with("https://"));
    }
}
